model: 
  name: v2
  config:
    num_notes: 88

window_length_seconds: 2.96

spectrogram:
  sample_rate: 44100
  hop_length: 2048
  f_min: 27.5
  n_bins: 116

midi:
  min_note: 21
  max_note: 109
  smoothing_radius: 2
  smoothing_std: 0.07

learning:
  learning_rate: 0.0005

loss:
  empty_weight: 6

train_dataloader:
  samples_per_epoch: 8196
  batch_size: 16


valid_dataloader:
  samples_per_epoch: 2048
  batch_size: 16
  